import { Rewards } from "../rewards";
import { LocationName } from "../types/LocationName";
import { RewardLocation, RewardLocationType } from "../types/RewardLocation";

export const prideLandsRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.BIGCHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Gorge",
		value: "11CE0042",
		reward: Rewards.SAVANNAH_MAP,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Gorge",
		value: "11CE004E",
		reward: Rewards.DARK_GEM,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Gorge",
		value: "11CE005A",
		reward: Rewards.MYTHRIL_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Elephant Graveyard",
		value: "11CE0066",
		reward: Rewards.FROST_GEM,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Elephant Graveyard",
		value: "11CE0072",
		reward: Rewards.MYTHRIL_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Elephant Graveyard",
		value: "11CE007E",
		reward: Rewards.BRIGHT_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Elephant Graveyard",
		value: "11CE008A",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Elephant Graveyard",
		value: "11CE0096",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.BIGCHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Pride Rock",
		value: "11CE00A2",
		reward: Rewards.PRIDE_ROCK_MAP,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Pride Rock",
		value: "11CE00AE",
		reward: Rewards.MYTHRIL_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Pride Rock",
		value: "11CE00BA",
		reward: Rewards.SERENITY_CRYSTAL,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Wildebeest Valley",
		value: "11CE00C6",
		reward: Rewards.ENERGY_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Wildebeest Valley",
		value: "11CE00D2",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Wildebeest Valley",
		value: "11CE00DE",
		reward: Rewards.MYTHRIL_GEM,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Wildebeest Valley",
		value: "11CE00EA",
		reward: Rewards.MYTHRIL_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Wildebeest Valley",
		value: "11CE00F6",
		reward: Rewards.LUCID_GEM,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Wastelands",
		value: "11CE0102",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Wastelands",
		value: "11CE010E",
		reward: Rewards.SERENITY_GEM,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Wastelands",
		value: "11CE011A",
		reward: Rewards.MYTHRIL_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Jungle",
		value: "11CE0126",
		reward: Rewards.SERENITY_GEM,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Jungle",
		value: "11CE0132",
		reward: Rewards.MYTHRIL_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Jungle",
		value: "11CE013E",
		reward: Rewards.SERENITY_CRYSTAL,
	},
	{
		type: RewardLocationType.BIGCHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Oasis",
		value: "11CE014A",
		reward: Rewards.OASIS_MAP,
	},
	{
		type: RewardLocationType.BIGCHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Oasis",
		value: "11CE0156",
		reward: Rewards.TORN_PAGES,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.PRIDE_LANDS,
		description: "Oasis",
		value: "11CE0162",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.BONUS,
		location: LocationName.PRIDE_LANDS,
		description: "Groundshaker",
		value: "21D10C18",
		reward: Rewards.THUNDER,
		secondVisit: true,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.PRIDE_LANDS,
		description: "Circle of Life",
		value: "11CE07B6",
		reward: Rewards.CIRCLE_OF_LIFE,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.PRIDE_LANDS,
		description: "Fire",
		value: "11CE07C2",
		reward: Rewards.FIRE,
	},
];
