import { Reward } from "../Reward";
import { RewardType } from "../RewardType";

export const bonusRewards: Reward[] = [
	{
		type: RewardType.ABILITY,
		name: "Aerial Recovery",
		value: "009E",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Guard",
		value: "0052",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Scan",
		value: "008A",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Slide Dash",
		value: "0108",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Aerial Sweep",
		value: "010D",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Upper Slash",
		value: "0089",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Retaliating Slash",
		value: "0111",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Counterguard",
		value: "010C",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Aerial Dive",
		value: "0230",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Trinity Limit",
		value: "00C6",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Auto Summon",
		value: "0185",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Dodge Slash",
		value: "0107",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Aerial Spiral",
		value: "010E",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Aerial Finish",
		value: "0110",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Summon Boost",
		value: "018F",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Finishing Leap",
		value: "010B",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Flash Step",
		value: "022F",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Vicinity Break",
		value: "0232",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Guard Break",
		value: "0109",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Magnet Burst",
		value: "0231",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Horizontal Slash",
		value: "010F",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Explosion",
		value: "010A",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Slapshot",
		value: "0106",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Combo Master",
		value: "021B",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Fire Upgrade",
		value: "0015",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Thunder Upgrade",
		value: "0017",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Reflect Upgrade",
		value: "0058",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Blizzard Upgrade",
		value: "0016",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Thunder Upgrade",
		value: "0017",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Reflect Upgrade",
		value: "0058",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Magnet Upgrade",
		value: "0057",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Fire Upgrade",
		value: "0015",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Thunder Upgrade",
		value: "0017",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Reflect Upgrade",
		value: "0058",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Magnet Upgrade",
		value: "0057",
		priority: 0,
	},
];
