import { Reward } from "../Reward";
import { RewardType } from "../RewardType";

export const donaldRewards: Reward[] = [
	{
		type: RewardType.ABILITY,
		name: "Donald Thunder",
		value: "00A7",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Donald Cure",
		value: "00A8",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Donald Fire",
		value: "00A5",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Donald Blizzard",
		value: "00A6",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Fantasia (Comet)",
		value: "00C7",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Flare Force (Duck Flare)",
		value: "00C8",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Draw",
		value: "0195",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Jackpot",
		value: "0196",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Lucky Lucky",
		value: "0197",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Fire Boost",
		value: "0198",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Blizzard Boost",
		value: "0199",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Thunder Boost",
		value: "019A",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "MP Rage",
		value: "019C",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "MP Hastera",
		value: "01A5",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Auto Limit",
		value: "01A1",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Hyper Healing",
		value: "01A3",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Auto Healing",
		value: "01A4",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Damage Control",
		value: "021E",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Hyper Healing",
		value: "01A3",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "MP Rage",
		value: "019C",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "MP Haste",
		value: "019D",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "MP Hastera",
		value: "01A5",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "MP Hastega",
		value: "01A6",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Thunder Boost",
		value: "019A",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Fire Boost",
		value: "0198",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Blizzard Boost",
		value: "0199",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Defender",
		value: "019E",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Item Boost",
		value: "019B",
		priority: 0,
	},
];
