import { Reward } from "../Reward";
import { RewardType } from "../RewardType";

export const goofyRewards: Reward[] = [
	{
		name: "Goofy Bash",
		value: "11D16F62",
		priority: 0,
		type: RewardType.ABILITY,
	},
	{
		type: RewardType.ABILITY,
		name: "Item Boost",
		value: "019B",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Goofy Turbo",
		value: "01A9",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Goofy Tornado",
		value: "01A7",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Tornado Fusion (Whirli-Goof)",
		value: "00C9",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Teamwork (Knocksmash)",
		value: "00CA",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Draw",
		value: "0195",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Jackpot",
		value: "0196",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Lucky Lucky",
		value: "0197",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "MP Rage",
		value: "019C",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Defender ",
		value: "019E",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Damage Control",
		value: "021E",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Second Chance ",
		value: "019F",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Once More",
		value: "01A0",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Auto Limit",
		value: "01A1",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Auto Change",
		value: "01A2",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Hyper Healing",
		value: "01A3",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Auto Healing",
		value: "01A4",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "MP Hastega",
		value: "01A6",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Item Boost",
		value: "019B",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Damage Control",
		value: "021E",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Protect",
		value: "0254",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Protectra",
		value: "0255",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Protectga",
		value: "0256",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Defender",
		value: "019E",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "Hyper Healing",
		value: "01A3",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "MP Haste",
		value: "019D",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "MP Hastera",
		value: "01A5",
		priority: 0,
	},
	{
		type: RewardType.ABILITY,
		name: "MP Rage",
		value: "019C",
		priority: 0,
	},
];
