import { Reward } from "../Reward";
import { RewardType } from "../RewardType";

export const popupRewards: Reward[] = [
	{
		type: RewardType.MAP,
		name: "Twilight Town Map",
		value: "00FF",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Munny Pouch (Olette)",
		value: "016A",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Struggle Trophy",
		value: "021A",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Namine's Sketches",
		value: "0170",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Mansion Map",
		value: "0214",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Munny Pouch (Mickey)",
		value: "0217",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Crystal Orb",
		value: "016B",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Star Seeker",
		value: "01E0",
		priority: 0,
	},
	{
		type: RewardType.FORM,
		name: "Valor Form",
		value: "001A",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Marketplace Map",
		value: "00FD",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Membership Card",
		value: "0171",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Blizzard Upgrade",
		value: "0016",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Encampment Area Map",
		value: "0070",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "AP Boost",
		value: "0117",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Village Area Map",
		value: "0071",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Hidden Dragon",
		value: "01E1",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Cure Upgrade",
		value: "0018",
		priority: 0,
	},
	{
		type: RewardType.SUMMON,
		name: "Baseball Charm",
		value: "017F",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Coliseum Map",
		value: "0086",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Olympus Stone",
		value: "0172",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Hero's Crest",
		value: "01E4",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Disney Castle Map",
		value: "0077",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Window of Time Map",
		value: "0206",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Monochrome",
		value: "01E5",
		priority: 0,
	},
	{
		type: RewardType.FORM,
		name: "Wisdom Form",
		value: "001B",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Isla de Muerta Map",
		value: "01FB",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Follow the Wind",
		value: "01E6",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Agrabah Map",
		value: "0078",
		priority: 0,
	},
	{
		type: RewardType.SUMMON,
		name: "Lamp Charm",
		value: "009F",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Magnet Upgrade",
		value: "0057",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Circle of Life",
		value: "01E7",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Fire Upgrade",
		value: "0015",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Seifer's Trophy",
		value: "016C",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Oathkeeper",
		value: "002A",
		priority: 0,
	},
	{
		type: RewardType.FORM,
		name: "Limit Form",
		value: "0233",
		priority: 0,
	},
	{
		type: RewardType.FORM,
		name: "Master Form",
		value: "001F",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Photon Debugger",
		value: "01E8",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Cure Upgrade",
		value: "0018",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Ice Cream",
		value: "0177",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Picture",
		value: "0178",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Rumbling Rose",
		value: "01EA",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Castle Walls Map",
		value: "005C",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Auron's Statue",
		value: "0173",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Guardian Soul",
		value: "01EB",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Cursed Medallion",
		value: "0174",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Ship Graveyard Map",
		value: "01FC",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Wishing Lamp",
		value: "01EC",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Presents",
		value: "0175",
		priority: 0,
	},
	{
		type: RewardType.MISCELLANEOUS,
		name: "Decoy Presents",
		value: "0176",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Decisive Pumpkin",
		value: "01ED",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Undersea Kingdom Map",
		value: "007B",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Mysterious Abyss",
		value: "01F0",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Blizzard Upgrade",
		value: "0016",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Orichalcum+",
		value: "0169",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Sweet Memories",
		value: "01EF",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Spooky Cave Map",
		value: "0081",
		priority: 0,
	},
	{
		type: RewardType.SPELL,
		name: "Cure Upgrade",
		value: "0018",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Orichalcum+",
		value: "0169",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Sleeping Lion",
		value: "01EE",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Fenrir",
		value: "01F3",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Bond of Flame",
		value: "01F2",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Two Become One",
		value: "021F",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Oblivion",
		value: "002B",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Castle That Never Was Map",
		value: "0218",
		priority: 0,
	},
	{
		type: RewardType.ARMOR,
		name: "Protect Belt",
		value: "004E",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Serenity Gem",
		value: "0167",
		priority: 0,
	},
	{
		type: RewardType.STAFF,
		name: "Rising Dragon",
		value: "009A",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Serenity Crystal",
		value: "0168",
		priority: 0,
	},
	{
		type: RewardType.SHIELD,
		name: "Genji Shield",
		value: "0091",
		priority: 0,
	},
	{
		type: RewardType.ACCESSORY,
		name: "Skillful Ring",
		value: "0027",
		priority: 0,
	},
	{
		type: RewardType.KEYBLADE,
		name: "Fatal Crest",
		value: "01F1",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Orichalcum+",
		value: "0169",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 1",
		value: "00E2",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 2",
		value: "00E3",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 3",
		value: "00E4",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 4",
		value: "00E5",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 5",
		value: "00E6",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 6",
		value: "00E7",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 7",
		value: "00E8",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 8",
		value: "00E9",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 9",
		value: "00EA",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 10",
		value: "00EB",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 11",
		value: "00EC",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 12",
		value: "00ED",
		priority: 0,
	},
	{
		type: RewardType.REPORT,
		name: "Secret Ansem's Report 13",
		value: "00EE",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Road to Discovery",
		value: "01D0",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Strength Beyond Strength",
		value: "01D1",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Book of Shadows",
		value: "01D2",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Cloaked Thunder",
		value: "01D3",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Eternal Blossom",
		value: "01D4",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Power Boost",
		value: "0114",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Defense Boost",
		value: "0116",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Defense Boost",
		value: "0116",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Lost Illusion",
		value: "0248",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Lost Illusion",
		value: "0248",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Lost Illusion",
		value: "0248",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Lost Illusion",
		value: "0248",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Lost Illusion",
		value: "0248",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Defense Boost",
		value: "0116",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Magic Boost",
		value: "0115",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "AP Boost",
		value: "0117",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "AP Boost",
		value: "0117",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Magic Boost",
		value: "0115",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Proof of Connection",
		value: "0251",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Manifest Illusion",
		value: "0249",
		priority: 0,
	},
];
