import { Reward } from "../Reward";
import { RewardType } from "../RewardType";

export const twilightTownRewards: Reward[] = [
	{
		type: RewardType.KEYBLADE,
		name: "Ultima Weapon",
		value: "01F4",
		priority: 0,
	},
	{
		type: RewardType.ARMOR,
		name: "Champion Belt",
		value: "0131",
		priority: 0,
	},
	{
		type: RewardType.STAFF,
		name: "Centurion",
		value: "0221",
		priority: 0,
	},
	{
		type: RewardType.ACCESSORY,
		name: "Medal",
		value: "0035",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Hi-Potion",
		value: "0002",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Hi-Potion",
		value: "0002",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "AP Boost",
		value: "0117",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Tent",
		value: "0083",
		priority: 0,
	},
	{
		type: RewardType.ACCESSORY,
		name: "Lucky Ring",
		value: "003F",
		priority: 0,
	},
	{
		type: RewardType.SHIELD,
		name: "Frozen Pride",
		value: "0228",
		priority: 0,
	},
	{
		type: RewardType.ACCESSORY,
		name: "Shadow Archive",
		value: "0039",
		priority: 0,
	},
	{
		type: RewardType.STAFF,
		name: "Nobody Lance",
		value: "009B",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Tent",
		value: "0083",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Hi-Potion",
		value: "0002",
		priority: 0,
	},
	{
		type: RewardType.ACCESSORY,
		name: "Shock Charm",
		value: "0084",
		priority: 0,
	},
	{
		type: RewardType.STAFF,
		name: "Shaman's Relic",
		value: "009C",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Hi-Potion",
		value: "0002",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Ether",
		value: "0003",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Ether",
		value: "0003",
		priority: 0,
	},
	{
		type: RewardType.ACCESSORY,
		name: "Full Bloom",
		value: "0040",
		priority: 0,
	},
	{
		type: RewardType.MAP,
		name: "Tower Map",
		value: "0215",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Mythril Stone",
		value: "015A",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Mythril Gem",
		value: "015B",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Orichalcum",
		value: "0179",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "AP Boost",
		value: "0117",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Mythril Crystal",
		value: "015C",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Orichalcum",
		value: "0179",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Mythril Crystal",
		value: "015C",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Orichalcum+",
		value: "0169",
		priority: 0,
	},
	{
		type: RewardType.SHIELD,
		name: "Akashic Record",
		value: "0092",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Mythril Crystal",
		value: "015C",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "AP Boost",
		value: "0117",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Mythril Crystal",
		value: "015C",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Mythril Stone",
		value: "015A",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Serenity Crystal",
		value: "0168",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Mythril Crystal",
		value: "015C",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Mythril Stone",
		value: "015A",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Orichalcum",
		value: "0179",
		priority: 0,
	},
	{
		type: RewardType.ITEM,
		name: "Ultimate Recipe",
		value: "01DF",
		priority: 0,
	},
];
