import { Enemies } from "../enemies";
import { LocationName } from "../LocationName";
import { EnemyLocation, EnemyLocationType } from "./EnemyLocation";

export const beastsCastleEnemyLocations: EnemyLocation[] = [
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C504CC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C5050C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C5054C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C5058C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C505CC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C5060C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C5064C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C5068C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C506CC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C5070C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C5074C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C5078C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C507CC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C5080C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C5084C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Parlor Shadows",
		value: "11C5088C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Thresholder Boss Fight",
		value: "11C55204",
		enemy: Enemies.THRESHOLDER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Thresholder Boss Fight",
		value: "11C55244",
		enemy: Enemies.POSSESSOR,
	},
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.BEASTS_CASTLE,
	// 	description: "Thresholder Boss Fight",
	// 	value: "11C552B0",
	// 	enemy: Enemies.???,
	// 	// | Gargoyle Knight |
	// },
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.BEASTS_CASTLE,
	// 	description: "Thresholder Boss Fight",
	// 	value: "11C552F0",
	// 	enemy: Enemies.???,
	// 	// | Gargoyle Knight |
	// },
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Thresholder Boss Fight",
		value: "11C55330",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Thresholder Boss Fight",
		value: "11C55370",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Thresholder Boss Fight",
		value: "11C553B0",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Thresholder Boss Fight",
		value: "11C553F0",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Thresholder Boss Fight",
		value: "11C55430",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Thresholder Boss Fight",
		value: "11C55470",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Thresholder Boss Fight",
		value: "11C554B0",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Thresholder Boss Fight",
		value: "11C554F0",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Thresholder Boss Fight",
		value: "11C55530",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Thresholder Boss Fight",
		value: "11C55570",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Beast Boss Fight",
		value: "11C4CBA0",
		enemy: Enemies.THE_BEAST,
	},
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.BEASTS_CASTLE,
	// 	description: "Shadow Stalker Boss Fight",
	// 	value: "11C59F9C",
	// 	enemy: Enemies.???,
	// 	// | Chandelier |
	// },
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.BEASTS_CASTLE,
	// 	description: "Shadow Stalker Boss Fight",
	// 	value: "11C5A010",
	// 	enemy: Enemies.???,
	// 	// | Window |
	// },
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.BEASTS_CASTLE,
	// 	description: "Shadow Stalker Boss Fight",
	// 	value: "11C5A3A0",
	// 	enemy: Enemies.???,
	// 	// | Pillar |
	// },
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Shadow Stalker Boss Fight",
		value: "11C5A360",
		enemy: Enemies.SHADOW_STALKER,
	},
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.BEASTS_CASTLE,
	// 	description: "Dark Thorn Boss Fight",
	// 	value: "11C5A16C",
	// 	enemy: Enemies.???,
	// 	// | Chandelier |
	// },
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Dark Thorn Boss Fight",
		value: "11C5A4D4",
		enemy: Enemies.DARK_THORN,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Ballroom Nobodies Fight",
		value: "11C5209C",
		enemy: Enemies.DRAGOON,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Ballroom Nobodies Fight",
		value: "11C520DC",
		enemy: Enemies.DRAGOON,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Ballroom Nobodies Fight",
		value: "11C5211C",
		enemy: Enemies.DRAGOON,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Ballroom Nobodies Fight",
		value: "11C5215C",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Ballroom Nobodies Fight",
		value: "11C5219C",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Entrance Hall Nobodies Fight",
		value: "11C500E4",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Entrance Hall Nobodies Fight",
		value: "11C50124",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Entrance Hall Nobodies Fight",
		value: "11C50164",
		enemy: Enemies.DRAGOON,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Entrance Hall Nobodies Fight",
		value: "11C501A4",
		enemy: Enemies.DRAGOON,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Entrance Hall Nobodies Fight",
		value: "11C501E4",
		enemy: Enemies.DRAGOON,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Entrance Hall Nobodies Fight",
		value: "11C50290",
		enemy: Enemies.DRAGOON,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Entrance Hall Nobodies Fight",
		value: "11C502D0",
		enemy: Enemies.DRAGOON,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Entrance Hall Nobodies Fight",
		value: "11C50310",
		enemy: Enemies.DRAGOON,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.BEASTS_CASTLE,
		description: "Xaldin Boss Fight",
		value: "11C5A0A8",
		enemy: Enemies.XALDIN,
	},
];
