import { Enemies } from "../enemies";
import { LocationName } from "../LocationName";
import { EnemyLocation, EnemyLocationType } from "./EnemyLocation";

export const halloweenTownEnemyLocations: EnemyLocation[] = [
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A528",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A568",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A5A8",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A5E8",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A628",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A668",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A6A8",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A6E8",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A728",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A768",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A7A8",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A7E8",
		enemy: Enemies.SHADOW_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A828",
		enemy: Enemies.SOLDIER_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A868",
		enemy: Enemies.SHADOW_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A8A8",
		enemy: Enemies.SHADOW_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A8E8",
		enemy: Enemies.SHADOW_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A928",
		enemy: Enemies.SHADOW_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A968",
		enemy: Enemies.SOLDIER_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A9A8",
		enemy: Enemies.SHADOW_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square Heartless",
		value: "11C4A9E8",
		enemy: Enemies.SHADOW_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Candy Cane Lane Heartless",
		value: "11C4F634",
		enemy: Enemies.DRILLER_MOLE_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Candy Cane Lane Heartless",
		value: "11C4F674",
		enemy: Enemies.DRILLER_MOLE_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Candy Cane Lane Heartless",
		value: "11C4F6B4",
		enemy: Enemies.TOY_SOLDIER_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Candy Cane Lane Heartless",
		value: "11C4F6F4",
		enemy: Enemies.DRILLER_MOLE_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Candy Cane Lane Heartless",
		value: "11C4F734",
		enemy: Enemies.TOY_SOLDIER_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Candy Cane Lane Heartless",
		value: "11C4F774",
		enemy: Enemies.TOY_SOLDIER_HT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Prison Keeper Boss Fight",
		value: "11C55570",
		enemy: Enemies.PRISON_KEEPER,
	},
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.HALLOWEEN_TOWN,
	// 	description: "Oogie Boogie Boss Fight",
	// 	value: "11C4C204",
	// 	enemy: Enemies.???,
	// },
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "LSB",
		value: "11C57570",
		enemy: Enemies.LOCK,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "LSB",
		value: "11C575B0",
		enemy: Enemies.SHOCK,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "LSB",
		value: "11C575F0",
		enemy: Enemies.BARREL,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Present Collecting Fight",
		value: "11C4ABB8",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Present Collecting Fight",
		value: "11C4ABF8",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Present Collecting Fight",
		value: "11C4AC38",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Present Collecting Fight",
		value: "11C4AC78",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Present Collecting Fight",
		value: "11C4ACB8",
		enemy: Enemies.GRAVEYARD_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Present Collecting Fight",
		value: "11C4ACF8",
		enemy: Enemies.GRAVEYARD_HT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Present Collecting Fight",
		value: "11C4AD38",
		enemy: Enemies.WIGHT_KNIGHT_HT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Experiment Boss Fight",
		value: "11C56120",
		enemy: Enemies.THE_EXPERIMENT,
	},
];
