import { Enemies } from "../enemies";
import { LocationName } from "../LocationName";
import { EnemyLocation, EnemyLocationType } from "./EnemyLocation";

export const landOfDragonsEnemyLocations: EnemyLocation[] = [
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Encampment Heartless",
		value: "11C48CD4",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Encampment Heartless",
		value: "11C48D14",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Encampment Heartless",
		value: "11C48D54",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Encampment Heartless",
		value: "11C48D94",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Encampment Heartless",
		value: "11C48DD4",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Encampment Heartless",
		value: "11C49118",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Encampment Heartless",
		value: "11C491C4",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Encampment Heartless",
		value: "11C49278",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Encampment Heartless",
		value: "11C492B8",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B09C",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B0DC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B11C",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B15C",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B19C",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B1DC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B21C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B25C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B29C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B2DC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B31C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B35C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B39C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B3DC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 1: The Surprise Attack",
		value: "11C5B41C",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 2: The Ambush",
		value: "11C5B760",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 2: The Ambush",
		value: "11C5B7A0",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 2: The Ambush",
		value: "11C5B7E0",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 2: The Ambush",
		value: "11C5B820",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 2: The Ambush",
		value: "11C5B860",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 2: The Ambush",
		value: "11C5B8A0",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 2: The Ambush",
		value: "11C5B8E0",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 2: The Ambush",
		value: "11C5B920",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 2: The Ambush",
		value: "11C5B9CC",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 2: The Ambush",
		value: "11C5BA0C",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 2: The Ambush",
		value: "11C5BA4C",
		enemy: Enemies.ASSAULT_RIDER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 2: The Ambush",
		value: "11C5BA8C",
		enemy: Enemies.ASSAULT_RIDER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 3: The Search",
		value: "11C49504",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 3: The Search",
		value: "11C49544",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 3: The Search",
		value: "11C49584",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 3: The Search",
		value: "11C495C4",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 3: The Search",
		value: "11C49604",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 3: The Search",
		value: "11C49644",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 3: The Search",
		value: "11C49684",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mission 3: The Search",
		value: "11C496C4",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58528",
		enemy: Enemies.SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58568",
		enemy: Enemies.SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C585A8",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58680",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C586C0",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58700",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C587DC",
		enemy: Enemies.ASSAULT_RIDER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C5881C",
		enemy: Enemies.ASSAULT_RIDER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C588F8",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58938",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C589E4",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58A24",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58AD0",
		enemy: Enemies.SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58B10",
		enemy: Enemies.SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58B50",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58BFC",
		enemy: Enemies.SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58C3C",
		enemy: Enemies.SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58C7C",
		enemy: Enemies.SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Mountain Trail Heartless",
		value: "11C58CBC",
		enemy: Enemies.SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C5791C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C5795C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C5799C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C579DC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57A1C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57A5C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57A9C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57ADC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57B1C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57B5C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57B9C",
		enemy: Enemies.ASSAULT_RIDER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57BDC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57C1C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57C5C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57C9C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57CDC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57D1C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57D5C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57D9C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57DDC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57E1C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57E5C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57E9C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57EDC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57F1C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57F5C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57F9C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C57FDC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C5801C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C5805C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C5809C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C580DC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C5811C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C5815C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C5819C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C581DC",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C5821C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C5825C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C5829C",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C58348",
		enemy: Enemies.ASSAULT_RIDER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Village Cave Heartless",
		value: "11C58388",
		enemy: Enemies.ASSAULT_RIDER,
	},
	// Rapid Thruster Swarm (Land of Dragons; 1st Visit)
	// 11C32160 0000???? - Bolt Tower (Beginning)
	// 11C321A0 0000???? - Bolt Tower
	// 11C321E0 0000???? - Bolt Tower
	// 11C32220 0000???? - Bolt Tower
	// 11C32260 0000???? - Bolt Tower
	// 11C322A0 0000???? - Bolt Tower
	// 11C32354 0000????
	// 11C32394 0000????
	// 11C323D4 0000????
	// 11C32414 0000????
	// 11C32454 0000????
	// 11C32494 0000????
	// 11C324D4 0000????
	// 11C32514 0000????
	// 11C32554 0000????
	// 11C32594 0000????
	// 11C325D4 0000????
	// 11C32614 0000????
	// 11C32654 0000????
	// 11C32694 0000????
	// 11C326D4 0000????
	// 11C32714 0000????
	// 11C32754 0000????
	// 11C32794 0000????
	// 11C327D4 0000????
	// 11C32814 0000????
	// 11C32854 0000????
	// 11C32894 0000????
	// 11C328D4 0000????
	// 11C32914 0000????
	// 11C32954 0000????
	// 11C32994 0000????
	// 11C329D4 0000????
	// 11C32A14 0000????
	// 11C32A54 0000????
	// 11C32A94 0000????
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (1st Visit)",
		value: "11C4CCC4",
		enemy: Enemies.BOLT_TOWER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (1st Visit)",
		value: "11C4CD04",
		enemy: Enemies.BOLT_TOWER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (1st Visit)",
		value: "11C4CD44",
		enemy: Enemies.BOLT_TOWER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (1st Visit)",
		value: "11C4CDF0",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (1st Visit)",
		value: "11C4CE30",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (1st Visit)",
		value: "11C4CE70",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (1st Visit)",
		value: "11C4CEB0",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4BEB0",
		enemy: Enemies.HAYABUSA,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4BE70",
		enemy: Enemies.SHAN_YU,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4BF24",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4BF64",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4BFA4",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4BFE4",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4C024",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4C064",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4C0A4",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4C0E4",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4C124",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4C164",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4C1A4",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4C1E4",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4C224",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4C264",
		enemy: Enemies.NIGHTWALKER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Shan-Yu Boss Fight",
		value: "11C4C2A4",
		enemy: Enemies.NIGHTWALKER,
	},
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.LAND_OF_DRAGONS,
	// 	description: "Riku? Boss Fight",
	// 	value: "11C32BB4",
	// 	enemy: Enemies.RIKU,
	// },
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (2nd Visit)",
		value: "11C4D024",
		enemy: Enemies.BOLT_TOWER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (2nd Visit)",
		value: "11C4D064",
		enemy: Enemies.BOLT_TOWER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (2nd Visit)",
		value: "11C4D0A4",
		enemy: Enemies.BOLT_TOWER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (2nd Visit)",
		value: "11C4D0E4",
		enemy: Enemies.BOLT_TOWER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (2nd Visit)",
		value: "11C4D1C0",
		enemy: Enemies.ASSAULT_RIDER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (2nd Visit)",
		value: "11C4D200",
		enemy: Enemies.ASSAULT_RIDER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Imperial Square Heartless Fight (2nd Visit)",
		value: "11C4D240",
		enemy: Enemies.ASSAULT_RIDER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Antechamber Nobodies Fight",
		value: "11C56664",
		enemy: Enemies.SNIPER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Antechamber Nobodies Fight",
		value: "11C566A4",
		enemy: Enemies.SNIPER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Antechamber Nobodies Fight",
		value: "11C566E4",
		enemy: Enemies.SNIPER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Antechamber Nobodies Fight",
		value: "11C56724",
		enemy: Enemies.SNIPER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Antechamber Nobodies Fight",
		value: "11C56764",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Antechamber Nobodies Fight",
		value: "11C567A4",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Antechamber Nobodies Fight",
		value: "11C567E4",
		enemy: Enemies.SNIPER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Antechamber Nobodies Fight",
		value: "11C56824",
		enemy: Enemies.SNIPER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Antechamber Nobodies Fight",
		value: "11C56864",
		enemy: Enemies.SNIPER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Antechamber Nobodies Fight",
		value: "11C568A4",
		enemy: Enemies.SNIPER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Antechamber Nobodies Fight",
		value: "11C568E4",
		enemy: Enemies.SNIPER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Antechamber Nobodies Fight",
		value: "11C56924",
		enemy: Enemies.SNIPER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.LAND_OF_DRAGONS,
		description: "Storm Rider Boss Fight",
		value: "11C4D324",
		enemy: Enemies.STORM_RIDER,
	},
];
