import { Enemies } from "../enemies";
import { LocationName } from "../LocationName";
import { EnemyLocation, EnemyLocationType } from "./EnemyLocation";

export const olympusEnemyLocations: EnemyLocation[] = [
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.OLYMPUS,
	// 	description: "Hades Chamber Boss Fight",
	// 	value: "11C48478",
	// 	enemy: Enemies.HADES_I,
	// },
	// {
	// 	type: EnemyLocationType.MOB_FIGHT,
	// 	location: LocationName.OLYMPUS,
	// 	description: "Hades Escape",
	// 	value: "11C591FC",
	// 	enemy: Enemies.HADES_I,
	// },
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59268",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C592A8",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C592E8",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59328",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59368",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C593A8",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C593E8",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59454",
		enemy: Enemies.LANCE_SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59494",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C594D4",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59514",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hade s Escape",
		value: "11C59554",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59594",
		enemy: Enemies.LANCE_SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59640",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59680",
		enemy: Enemies.LANCE_SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C596C0",
		enemy: Enemies.LANCE_SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hade s Escape",
		value: "11C59700",
		enemy: Enemies.LARGE_BODY,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59740",
		enemy: Enemies.LANCE_SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59780",
		enemy: Enemies.LANCE_SOLDIER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C597C0",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59800",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59840",
		enemy: Enemies.SHADOW,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Escape",
		value: "11C59880",
		enemy: Enemies.SHADOW,
	},
	// {
	//  type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.OLYMPUS,
	// 	description: "Cerberus Boss Fight",
	// 	value: "11C4EF2C",
	// 	enemy: Enemies.???,
	// 	// | Boulder |
	// },
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.OLYMPUS,
	// 	description: "Cerberus Boss Fight",
	// 	value: "11C4EF6C",
	// 	enemy: Enemies.???,
	// 	// | Boulder |
	// },
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Cerberus Boss Fight",
		value: "11C4EDF8",
		enemy: Enemies.CERBERUS,
	},
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.OLYMPUS,
	// 	description: "Demyx I Boss Fight",
	// 	value: "11C527FC",
	// 	enemy: Enemies.???,
	// 	// | Demyx I |
	// },
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.OLYMPUS,
	// 	description: "Pete I Boss Fight",
	// 	value: "11C4F4D0",
	// 	enemy: Enemies.PETE_OC_I,
	// },
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Pete II Boss Fight",
		value: "11C4FB08",
		enemy: Enemies.PETE_OC_II,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Pete II Boss Fight",
		value: "11C4FBB4",
		enemy: Enemies.TRICK_GHOST,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Pete II Boss Fight",
		value: "11C4FBF4",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Pete II Boss Fight",
		value: "11C4FC34",
		enemy: Enemies.TRICK_GHOST,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Pete II Boss Fight",
		value: "11C4FC74",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Pete II Boss Fight",
		value: "11C4FCB4",
		enemy: Enemies.HOOK_BAT,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Pete II Boss Fight",
		value: "11C4FCF4",
		enemy: Enemies.HOOK_BAT,
	},
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.OLYMPUS,
	// 	description: "Hydra Boss Fight",
	// 	value: "11C566C4",
	// 	enemy: Enemies.HYDRA,
	// },
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Round 1",
		value: "11C4BCDC",
		enemy: Enemies.DRILLER_MOLE,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Round 1",
		value: "11C4BD1C",
		enemy: Enemies.TORNADO_STEP,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Round 1",
		value: "11C4BD5C",
		enemy: Enemies.TORNADO_STEP,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Round 1",
		value: "11C4BD9C",
		enemy: Enemies.MORNING_STAR,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Round 1",
		value: "11C4BE1C",
		enemy: Enemies.DRILLER_MOLE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Round 1",
		value: "11C4BE5C",
		enemy: Enemies.DRILLER_MOLE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Semifinals",
		value: "11C4BFD0",
		enemy: Enemies.CRESCENDO,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Semifinals",
		value: "11C4C010",
		enemy: Enemies.MINUTE_BOMB,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Semifinals",
		value: "11C4C050",
		enemy: Enemies.MINUTE_BOMB,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Semifinals",
		value: "11C4C090",
		enemy: Enemies.MINUTE_BOMB,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Semifinals",
		value: "11C4C0D0",
		enemy: Enemies.MINUTE_BOMB,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Semifinals",
		value: "11C4C110",
		enemy: Enemies.CRIMSON_JAZZ,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Semifinals",
		value: "11C4C150",
		enemy: Enemies.MINUTE_BOMB,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Cup - Semifinals",
		value: "11C4C190",
		enemy: Enemies.MINUTE_BOMB,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades' Chamber Nobodies Fight",
		value: "11C486D8",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades' Chamber Nobodies Fight",
		value: "11C48718",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades' Chamber Nobodies Fight",
		value: "11C48758",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades' Chamber Nobodies Fight",
		value: "11C48798",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades' Chamber Nobodies Fight",
		value: "11C487D8",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades' Chamber Nobodies Fight",
		value: "11C48818",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades' Chamber Nobodies Fight",
		value: "11C48858",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades' Chamber Nobodies Fight",
		value: "11C48898",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades' Chamber Nobodies Fight",
		value: "11C488D8",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades' Chamber Nobodies Fight",
		value: "11C48918",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades' Chamber Nobodies Fight",
		value: "11C48958",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Boss Phase I",
		value: "11C5BF7C",
		enemy: Enemies.HADES_I,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.OLYMPUS,
		description: "Hades Boss Phase II",
		value: "11C5C0B0",
		enemy: Enemies.HADES_II,
	},
];
