import { Enemies } from "../enemies";
import { LocationName } from "../LocationName";
import { EnemyLocation, EnemyLocationType } from "./EnemyLocation";

export const simulatedTwilightTownEnemyLocations: EnemyLocation[] = [
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Seifer (Tutorial)",
		value: "11C36D8C",
		enemy: Enemies.SEIFER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Seifer (Day 1)",
		value: "11C36EC0",
		enemy: Enemies.SEIFER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Dusk (1st Fight with Struggle Bat)",
		value: "11C443A4",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Dusk (1st Fight with Kingdom Key)",
		value: "11C444D8",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Dusk (3rd Day; Sandlot)",
		value: "11C36FF4",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Station of Serenity Nobodies",
		value: "11C58C0C",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Station of Serenity Nobodies",
		value: "11C58C4C",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Station of Serenity Nobodies",
		value: "11C58C8C",
		enemy: Enemies.DUSK,
	},
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.SIMULATED_TWILIGHT_TOWN,
	// 	description: "Twilight Thorn Boss Fight",
	// 	value: "11C59E24",
	// 	enemy: Enemies.TWILIGHT_THORN,
	// },
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Hayner (Struggle Tournament)",
		value: "11C269AC",
		enemy: Enemies.HAYNER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi (Struggle Tournament)",
		value: "11C26BF0",
		enemy: Enemies.VIVI_STRUGGLE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Sandlot (Struggle Tournament) Nobodies",
		value: "11C26D24",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Sandlot (Struggle Tournament) Nobodies",
		value: "11C26D64",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Sandlot (Struggle Tournament) Nobodies",
		value: "11C26DA4",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Axel I Boss Fight",
		value: "11C26ED8",
		enemy: Enemies.AXEL_I,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Setzer (Struggle Tournament)",
		value: "11C2700C",
		enemy: Enemies.SETZER,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Seifer (Day 4)",
		value: "11C375E4",
		enemy: Enemies.SEIFER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58B68",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58BA8",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58BE8",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58C28",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58C68",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58CA8",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58CE8",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58D28",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58D68",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58DA8",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58DE8",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58E28",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58E68",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Vivi Clones",
		value: "11C58EA8",
		enemy: Enemies.VIVI_CLONE,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Shadow Roxas (7 Wonders)",
		value: "11C53F9C",
		enemy: Enemies.SHADOW_ROXAS,
	},
	// {
	// 	type: EnemyLocationType.MOB_FIGHT,
	// 	location: LocationName.SIMULATED_TWILIGHT_TOWN,
	// 	description: "Sunset Hill Bag Mini-Game",
	// 	value: "11C509BC",
	// 	enemy: Enemies.DUSK,
	// 	/// ???????
	// },
	// {
	// 	type: EnemyLocationType.MOB_FIGHT,
	// 	location: LocationName.SIMULATED_TWILIGHT_TOWN,
	// 	description: "Sunset Hill Bag Mini-Game",
	// 	value: "11C509FC",
	// 	enemy: Enemies.DUSK,
	// 	/// ???????
	// },
	// {
	// 	type: EnemyLocationType.MOB_FIGHT,
	// 	location: LocationName.SIMULATED_TWILIGHT_TOWN,
	// 	description: "Sunset Hill Bag Mini-Game",
	// 	value: "11C50A3C",
	// 	enemy: Enemies.DUSK,
	// 	/// ???????
	// },
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Back Alley Nobodies",
		value: "11C50104",
		enemy: Enemies.ASSASSIN,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Back Alley Nobodies",
		value: "11C50144",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Back Alley Nobodies",
		value: "11C50184",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Mansion: Basement Hall Nobodies",
		value: "11C55B94",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Mansion: Basement Hall Nobodies",
		value: "11C55BD4",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Mansion: Basement Hall Nobodies",
		value: "11C55C14",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Mansion: Basement Hall Nobodies",
		value: "11C55C54",
		enemy: Enemies.DUSK,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Mansion: Basement Hall Nobodies",
		value: "11C55C94",
		enemy: Enemies.ASSASSIN,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Mansion: Basement Hall Nobodies",
		value: "11C55CD4",
		enemy: Enemies.ASSASSIN,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SIMULATED_TWILIGHT_TOWN,
		description: "Axel II Boss Fight",
		value: "11C5AF88",
		enemy: Enemies.AXEL_II,
	},
];
