import { Enemies } from "../enemies";
import { LocationName } from "../LocationName";
import { EnemyLocation, EnemyLocationType } from "./EnemyLocation";

export const spaceParanoidsEnemyLocations: EnemyLocation[] = [
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Hostile Program Boss Fight",
		value: "11C56530",
		enemy: Enemies.HOSTILE_PROGRAM,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Game Grid Heartless Fight",
		value: "11C56184",
		enemy: Enemies.DEVASTATOR,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Game Grid Heartless Fight",
		value: "11C561C4",
		enemy: Enemies.DEVASTATOR,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Game Grid Heartless Fight",
		value: "11C56204",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Game Grid Heartless Fight",
		value: "11C56244",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Game Grid Heartless Fight",
		value: "11C56284",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Game Grid Heartless Fight",
		value: "11C562C4",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Game Grid Heartless Fight",
		value: "11C56304",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Game Grid Heartless Fight",
		value: "11C56344",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "I/O Tower Heartless Fight",
		value: "11C566D0",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "I/O Tower Heartless Fight",
		value: "11C56710",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "I/O Tower Heartless Fight",
		value: "11C56750",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "I/O Tower Heartless Fight",
		value: "11C56790",
		enemy: Enemies.DEVASTATOR,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "I/O Tower Heartless Fight",
		value: "11C567D0",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "I/O Tower Heartless Fight",
		value: "11C56810",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "I/O Tower Heartless Fight",
		value: "11C56850",
		enemy: Enemies.DEVASTATOR,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "I/O Tower Heartless Fight",
		value: "11C56890",
		enemy: Enemies.DEVASTATOR,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "I/O Tower Heartless Fight",
		value: "11C568D0",
		enemy: Enemies.DEVASTATOR,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59864",
		enemy: Enemies.DEVASTATOR,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C598A4",
		enemy: Enemies.DEVASTATOR,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C598E4",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59990",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C599D0",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59A10",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59AEC",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59B2C",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59B6C",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59BAC",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59BEC",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59C2C",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59C6C",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59CAC",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59CEC",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59D2C",
		enemy: Enemies.MAGNUM_LOADER,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59E10",
		enemy: Enemies.DEVASTATOR,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59E50",
		enemy: Enemies.DEVASTATOR,
	},
	{
		type: EnemyLocationType.MOB_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Solar Sailer Heartless",
		value: "11C59E90",
		enemy: Enemies.DEVASTATOR,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Sark Boss Fight",
		value: "11C4FCC4",
		enemy: Enemies.SARK,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Sark Boss Fight",
		value: "11C4FD44",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Sark Boss Fight",
		value: "11C4FD84",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Sark Boss Fight",
		value: "11C4FDC4",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "Sark Boss Fight",
		value: "11C4FE04",
		enemy: Enemies.STRAFER_FORCED_FIGHTS,
	},
	{
		type: EnemyLocationType.BOSS_FIGHT,
		location: LocationName.SPACE_PARANOIDS,
		description: "MCP Boss Fight",
		value: "11C4FFB8",
		enemy: Enemies.SARK_LARGE,
	},
	// {
	// 	type: EnemyLocationType.BOSS_FIGHT,
	// 	location: LocationName.SPACE_PARANOIDS,
	// 	description: "MCP Boss Fight",
	// 	value: "11C4FF78",
	// 	enemy: Enemies.???,
	// },
];
