import { Rewards } from "../rewards";
import { RewardLocation, RewardLocationType } from "./RewardLocation";

export const beastsCastleRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (Courtyard)",
		value: "11CDFBF2",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (Courtyard)",
		value: "11CDFBFE",
		reward: Rewards.HI_POTION,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (Courtyard)",
		value: "11CDFC0A",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.BIGCHEST,
		description: "Beast's Castle (Belle's Room)",
		value: "11CDFC16",
		reward: Rewards.CASTLE_MAP,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (Belle's Room)",
		value: "11CDFC22",
		reward: Rewards.MEGA_RECIPE,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (The East Wing)",
		value: "11CDFC2E",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (The East Wing)",
		value: "11CDFC3A",
		reward: Rewards.TENT,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (The West Hall)",
		value: "11CDFC46",
		reward: Rewards.HI_POTION,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (The West Hall)",
		value: "11CDFC52",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (The West Hall)",
		value: "11CDFC5E",
		reward: Rewards.POWER_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (The West Hall)",
		value: "11CDFC6A",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (The West Hall)",
		value: "11CDFC76",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (The West Hall)",
		value: "11CDFC82",
		reward: Rewards.BRIGHT_STONE,
	},
	{
		type: RewardLocationType.BIGCHEST,
		description: "Beast's Castle (Dungeon)",
		value: "11CDFC8E",
		reward: Rewards.BASEMENT_MAP,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (Dungeon)",
		value: "11CDFC9A",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (Secret Passage)",
		value: "11CDFCA6",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (Secret Passage)",
		value: "11CDFCB2",
		reward: Rewards.HI_POTION,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (Secret Passage)",
		value: "11CDFCBE",
		reward: Rewards.LUCID_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (The West Wing)",
		value: "11CDFCCA",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (The West Wing)",
		value: "11CDFCD6",
		reward: Rewards.TENT,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Beast's Castle (The Beast's Room)",
		value: "11CDFCE2",
		reward: Rewards.BLAZING_SHARD,
	},
	{
		type: RewardLocationType.BONUS,
		description: "Thresholder",
		value: "21D10758",
		reward: Rewards.UPPER_SLASH,
	},
	{
		type: RewardLocationType.BONUS,
		description: "Dark Thorn",
		value: "21D10788",
		reward: Rewards.RETALIATING_SLASH,
	},
	{
		type: RewardLocationType.BONUS,
		description: "Xaldin",
		value: "21D107C8",
		reward: Rewards.REFLECT,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Cure Element (Beast's Castle)",
		value: "11CE06F6",
		reward: Rewards.CURE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Rumbling Rose",
		value: "11CE0852",
		reward: Rewards.RUMBLING_ROSE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Castle Walls Map",
		value: "11CE085E",
		reward: Rewards.CASTLE_WALLS_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 4 (Xaldin)",
		value: "11CE09C6",
		reward: Rewards.REPORT_FOUR,
	},
];
