import { Rewards } from "../rewards";
import { RewardLocation, RewardLocationType } from "./RewardLocation";

export const donaldRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.DONALD,
		description: "Starting Ability (Donald)",
		value: "11D16EE0",
		reward: Rewards.DONALD_THUNDER,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Starting Ability (Donald)",
		value: "11D16EE2",
		reward: Rewards.DONALD_CURE,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Thresholder",
		value: "21D10768",
		reward: Rewards.DONALD_FIRE,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Demyx (Olympus Coliseum)",
		value: "21D11008",
		reward: Rewards.MP_RAGE,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Pete (Steamboat Fight)",
		value: "11D10998",
		reward: Rewards.DONALD_FANTASIA,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Pete (Steamboat Fight)",
		value: "11D1099A",
		reward: Rewards.AUTO_LIMIT,
	},
	{
		type: RewardLocationType.DONALD,
		description: "The Interceptor Medallion Fight",
		value: "21D110C8",
		reward: Rewards.DRAW,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Abu Escort",
		value: "21D10DC8",
		reward: Rewards.DONALD_BLIZZARD,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Prison Keeper",
		value: "21D109F8",
		reward: Rewards.HYPER_HEALING,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Scar",
		value: "21D10BE8",
		reward: Rewards.FIRE_BOOST,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Datascape Computers",
		value: "21D10E28",
		reward: Rewards.THUNDER_BOOST,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Demyx",
		value: "21D10BB8",
		reward: Rewards.BLIZZARD_BOOST,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Xaldin",
		value: "21D107D8",
		reward: Rewards.AUTO_HEALING,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Grim Reaper 2",
		value: "21D10AF8",
		reward: Rewards.DONALD_FLARE_FORCE,
	},
	{
		type: RewardLocationType.DONALD,
		description: "The Experiment",
		value: "21D10A78",
		reward: Rewards.JACKPOT,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Solar Sailer Heartless",
		value: "21D11088",
		reward: Rewards.MP_HASTERA,
	},
	{
		type: RewardLocationType.DONALD,
		description: "The Old Mansion Nobodies",
		value: "21D10FC8",
		reward: Rewards.LUCKY_LUCKY,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Mage's Staff",
		value: "11CDF236",
		reward: Rewards.DAMAGE_CONTROL,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Hammer Staff",
		value: "11CDF246",
		reward: Rewards.HYPER_HEALING,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Victory Bell",
		value: "11CDF256",
		reward: Rewards.MP_RAGE,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Comet Staff",
		value: "11CDF276",
		reward: Rewards.MP_HASTE,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Lord's Broom",
		value: "11CDF286",
		reward: Rewards.MP_HASTERA,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Wisdom Wand",
		value: "11CDF296",
		reward: Rewards.MP_HASTEGA,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Meteor Staff",
		value: "11CDF266",
		reward: Rewards.THUNDER_BOOST,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Rising Dragon",
		value: "11CDF2A6",
		reward: Rewards.FIRE_BOOST,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Shaman's Relic",
		value: "11CDF2C6",
		reward: Rewards.BLIZZARD_BOOST,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Shaman's Relic+",
		value: "11CDF706",
		reward: Rewards.DEFENDER,
	},
	{
		type: RewardLocationType.DONALD,
		description: "Nobody Lance",
		value: "11CDF2B6",
		reward: Rewards.ITEM_BOOST,
	},
];
