import { Rewards } from "../rewards";
import { LocationName } from "../types/LocationName";
import { RewardLocation, RewardLocationType } from "../types/RewardLocation";

export const halloweenTownRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.CHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Graveyard",
		value: "11CDFD96",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Graveyard",
		value: "11CDFDA2",
		reward: Rewards.SERENITY_GEM,
	},
	{
		type: RewardLocationType.BIGCHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Dr. Finklestein's Lab",
		value: "11CDFDAE",
		reward: Rewards.HALLOWEEN_TOWN_MAP,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square",
		value: "11CDFDBA",
		reward: Rewards.MYTHRIL_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Halloween Town Square",
		value: "11CDFDC6",
		reward: Rewards.ENERGY_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Hinterlands",
		value: "11CDFDD2",
		reward: Rewards.LIGHTNING_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Hinterlands",
		value: "11CDFDDE",
		reward: Rewards.MYTHRIL_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Hinterlands",
		value: "11CDFDEA",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Candy Cane Lane",
		value: "11CDFDF6",
		reward: Rewards.MEGA_POTION,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Candy Cane Lane",
		value: "11CDFE02",
		reward: Rewards.MYTHRIL_GEM,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Candy Cane Lane",
		value: "11CDFE0E",
		reward: Rewards.LIGHTNING_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Candy Cane Lane",
		value: "11CDFE1A",
		reward: Rewards.MYTHRIL_STONE,
	},
	{
		type: RewardLocationType.BIGCHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Santa's House",
		value: "11CDFE26",
		reward: Rewards.CHRISTMAS_TOWN_MAP,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Santa's House",
		value: "11CDFE32",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.BONUS,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Prison Keeper",
		value: "21D109E8",
		reward: Rewards.FLASH_STEP,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Magnet",
		value: "11CE07AA",
		reward: Rewards.MAGNET,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Present",
		value: "11CE08BE",
		reward: Rewards.PRESENTS,
		secondVisit: true,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Decoy Presents",
		value: "11CE08CA",
		reward: Rewards.DECOY_PRESENTS,
		secondVisit: true,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.HALLOWEEN_TOWN,
		description: "Decisive Pumpkin",
		value: "11CE08D6",
		reward: Rewards.DECISIVE_PUMPKIN,
		secondVisit: true,
	},
];
