import { Rewards } from "../rewards";
import { RewardLocation, RewardLocationType } from "./RewardLocation";

export const portRoyalRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.BIGCHEST,
		description: "Port Royal (Rampart)",
		value: "11CDFE3E",
		reward: Rewards.NAVAL_MAP,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Rampart)",
		value: "11CDFE4A",
		reward: Rewards.MYTHRIL_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Rampart)",
		value: "11CDFE56",
		reward: Rewards.DARK_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Town)",
		value: "11CDFE62",
		reward: Rewards.DARK_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Town)",
		value: "11CDFE6E",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Town)",
		value: "11CDFE7A",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Town)",
		value: "11CDFE86",
		reward: Rewards.MYTHRIL_GEM,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Cave Mouth)",
		value: "11CDFE92",
		reward: Rewards.BRIGHT_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Cave Mouth)",
		value: "11CDFE9E",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Powder Store)",
		value: "11CDFEAA",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Powder Store)",
		value: "11CDFEB6",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Moonlight Nook)",
		value: "11CDFEC2",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Moonlight Nook)",
		value: "11CDFECE",
		reward: Rewards.SERENITY_GEM,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Moonlight Nook)",
		value: "11CDFEDA",
		reward: Rewards.POWER_STONE,
	},
	{
		type: RewardLocationType.BIGCHEST,
		description: "Port Royal (The Interceptor's Hold)",
		value: "11CDFEE6",
		reward: Rewards.FEATHER_CHARM,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Seadrift Keep)",
		value: "11CDFEF2",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Seadrift Keep)",
		value: "11CDFEFE",
		reward: Rewards.ORICHALCUM,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Seadrift Keep)",
		value: "11CDFF0A",
		reward: Rewards.METEOR_STAFF,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Seadrift Row)",
		value: "11CDFF16",
		reward: Rewards.SERENITY_GEM,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Seadrift Row)",
		value: "11CDFF22",
		reward: Rewards.KING_RECIPE,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Port Royal (Seadrift Row)",
		value: "11CDFF2E",
		reward: Rewards.MYTHRIL_CRYSTAL,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Isla de Muerta Map",
		value: "11CE077A",
		reward: Rewards.ISLA_DE_MUERTA_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Follow the Wind",
		value: "11CE0786",
		reward: Rewards.FOLLOW_THE_WIND,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Cursed Medallion",
		value: "11CE086A",
		reward: Rewards.CURSED_MEDALLION,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Ship Graveyard Map",
		value: "11CE0876",
		reward: Rewards.SHIP_GRAVEYARD_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 6 (Grim Reaper 2)",
		value: "11CE09DE",
		reward: Rewards.REPORT_SIX,
	},
];
