import { Rewards } from "../rewards";
import { LocationName } from "../types/LocationName";
import { RewardLocation, RewardLocationType } from "../types/RewardLocation";

export const twilightTownRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "The Old Mansion",
		value: "11CE022E",
		reward: Rewards.POTION,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "The Old Mansion",
		value: "11CE023A",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "The Woods",
		value: "11CE0246",
		reward: Rewards.POTION,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "The Woods",
		value: "11CE0252",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "The Woods",
		value: "11CE025E",
		reward: Rewards.HI_POTION,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Tram Common",
		value: "11CE026A",
		reward: Rewards.HI_POTION,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Tram Common",
		value: "11CE0276",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Tram Common",
		value: "11CE0282",
		reward: Rewards.TENT,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Tram Common",
		value: "11CE028E",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Tram Common",
		value: "11CE029A",
		reward: Rewards.POTION,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Tram Common",
		value: "11CE02A6",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Tram Common",
		value: "11CE02B2",
		reward: Rewards.POTION,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Central Station",
		value: "11CE02BE",
		reward: Rewards.TENT,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Central Station",
		value: "11CE02CA",
		reward: Rewards.HI_POTION,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Central Station",
		value: "11CE02D6",
		reward: Rewards.ETHER,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "The Tower",
		value: "11CE02E2",
		reward: Rewards.POTION,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "The Tower",
		value: "11CE02EE",
		reward: Rewards.HI_POTION,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "The Tower",
		value: "11CE02FA",
		reward: Rewards.ETHER,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Tower Entryway",
		value: "11CE0306",
		reward: Rewards.ETHER,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Tower Entryway",
		value: "11CE0312",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.BIGCHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Sorcerer's Loft",
		value: "11CE031E",
		reward: Rewards.TOWER_MAP,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Tower Wardrobe",
		value: "11CE032A",
		reward: Rewards.MYTHRIL_STONE,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Underground Concourse",
		value: "11CE0336",
		reward: Rewards.MYTHRIL_GEM,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Underground Concourse",
		value: "11CE0342",
		reward: Rewards.ORICHALCUM,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Underground Concourse",
		value: "11CE034E",
		reward: Rewards.AP_BOOST,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Underground Concourse",
		value: "11CE035A",
		reward: Rewards.MYTHRIL_CRYSTAL,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Tunnelway",
		value: "11CE0366",
		reward: Rewards.ORICHALCUM,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Tunnelway",
		value: "11CE0372",
		reward: Rewards.MYTHRIL_CRYSTAL,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Sunset Terrace",
		value: "11CE037E",
		reward: Rewards.ORICHALCUM_PLUS,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Sunset Terrace",
		value: "11CE038A",
		reward: Rewards.MYTHRIL_SHARD,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Sunset Terrace",
		value: "11CE0396",
		reward: Rewards.MYTHRIL_CRYSTAL,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Sunset Terrace",
		value: "11CE03A2",
		reward: Rewards.AP_BOOST,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Mansion Foyer",
		value: "11CE03AE",
		reward: Rewards.MYTHRIL_CRYSTAL,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Mansion Foyer",
		value: "11CE03BA",
		reward: Rewards.MYTHRIL_STONE,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Mansion Foyer",
		value: "11CE03C6",
		reward: Rewards.SERENITY_CRYSTAL,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Mansion Dining Room",
		value: "11CE03D2",
		reward: Rewards.MYTHRIL_CRYSTAL,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Mansion Dining Room",
		value: "11CE03DE",
		reward: Rewards.MYTHRIL_STONE,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Mansion Library",
		value: "11CE03EA",
		reward: Rewards.ORICHALCUM,
		secondVisit: true,
	},
	{
		type: RewardLocationType.CHEST,
		location: LocationName.TWILIGHT_TOWN,
		description: "Mansion Basement Corridor",
		value: "11CE03F6",
		reward: Rewards.ULTIMATE_RECIPE,
		secondVisit: true,
	},
	{
		type: RewardLocationType.BONUS,
		location: LocationName.TWILIGHT_TOWN,
		description: "Betwixt and Between Nobodies",
		value: "21D110E8",
		reward: Rewards.SLAPSHOT,
		secondVisit: true,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.TWILIGHT_TOWN,
		description: "Munny Pouch (Mickey)",
		value: "11CE065A",
		reward: Rewards.MUNNY_POUCH_MICKEY,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.TWILIGHT_TOWN,
		description: "Crystal Orb",
		value: "11CE0666",
		reward: Rewards.CRYSTAL_ORB,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.TWILIGHT_TOWN,
		description: "Star Seeker",
		value: "11CE0672",
		reward: Rewards.STAR_SEEKER,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.TWILIGHT_TOWN,
		description: "Valor Form",
		value: "11CE067E",
		reward: Rewards.VALOR_FORM,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.TWILIGHT_TOWN,
		description: "Seifer's Trophy",
		value: "11CE07E6",
		reward: Rewards.SEIFERS_TROPHY,
		secondVisit: true,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.TWILIGHT_TOWN,
		description: "Oathkeeper",
		value: "11CE07F2",
		reward: Rewards.OATHKEEPER,
		secondVisit: true,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.TWILIGHT_TOWN,
		description: "Limit Form",
		value: "11CE07FE",
		reward: Rewards.LIMIT_FORM,
		secondVisit: true,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.TWILIGHT_TOWN,
		description: "Bond of Flame",
		value: "11CE0966",
		reward: Rewards.BOND_OF_FLAME,
		secondVisit: true,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.TWILIGHT_TOWN,
		description: "Secret Ansem's Report 2 (Station Plaza Nobodies)",
		value: "11CE09AE",
		reward: Rewards.REPORT_TWO,
		secondVisit: true,
	},
	{
		type: RewardLocationType.POPUP,
		location: LocationName.TWILIGHT_TOWN,
		description: "Secret Ansem's Report 10 (Twilight Town 3)",
		value: "11CE0A0E",
		reward: Rewards.REPORT_TEN,
		secondVisit: true,
	},
];
