import { RewardLocation } from "../RewardLocation";
import { RewardLocationType } from "../RewardLocationType";

export const bonusRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.BONUS,
		description: "Station of Serenity Dusks",
		value: "21D10FA8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Twilight Thorn",
		value: "21D10CB8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Axel 1",
		value: "21D11278",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Bailey Nobodies",
		value: "21D10E98",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Village Cave Heartless",
		value: "21D10DF8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Shan-Yu",
		value: "21D108C8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Thresholder",
		value: "21D10758",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Dark Thorn",
		value: "21D10788",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Cerberus",
		value: "21D10808",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Phil's Training (Maniac)",
		value: "21D10FE8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Pete (Olympus Coliseum)",
		value: "21D10828",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Hydra",
		value: "21D10858",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Queen Minnie Escort",
		value: "21D10D28",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Pete (Steamboat Fight)",
		value: "21D10988",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Pete (Timeless River)",
		value: "21D109B8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "The Interceptor Medallion Fight",
		value: "21D110B8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Captain Barbossa",
		value: "21D10AA8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Abu Escort",
		value: "21D10DB8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Volcanic Lord & Blizzard Lord",
		value: "21D10CE8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Prison Keeper",
		value: "21D109E8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Hostile Program",
		value: "21D10C38",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Demyx (Hollow Bastion)",
		value: "21D10BA8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "1,000 Heartless",
		value: "21D11068",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Storm Rider",
		value: "21D10908",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Xaldin",
		value: "21D107C8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Hades",
		value: "21D10888",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Grim Reaper 1",
		value: "21D11028",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Grim Reaper 2",
		value: "21D10AE8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Genie Jafar",
		value: "21D10978",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Groundshaker",
		value: "21D10C18",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Solar Sailer Heartless",
		value: "21D11078",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "MCP",
		value: "21D10C78",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Betwixt and Between Nobodies",
		value: "21D110E8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Roxas",
		value: "21D111E8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.BONUS,
		description: "Luxord",
		value: "21D10B58",
		priority: 0,
		exclude: [],
	},
];
