import { RewardLocation } from "../RewardLocation";
import { RewardLocationType } from "../RewardLocationType";

export const donaldRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.DONALD,
		description: "Starting Ability (Donald)",
		value: "11D16EE0",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Starting Ability (Donald)",
		value: "11D16EE2",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Thresholder",
		value: "21D10768",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Demyx (Olympus Coliseum)",
		value: "21D11008",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Pete (Steamboat Fight)",
		value: "11D10998",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Pete (Steamboat Fight)",
		value: "11D1099A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "The Interceptor Medallion Fight",
		value: "21D110C8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Abu Escort",
		value: "21D10DC8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Prison Keeper",
		value: "21D109F8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Scar",
		value: "21D10BE8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Datascape Computers",
		value: "21D10E28",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Demyx",
		value: "21D10BB8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Xaldin",
		value: "21D107D8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Grim Reaper 2",
		value: "21D10AF8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "The Experiment",
		value: "21D10A78",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Solar Sailer Heartless",
		value: "21D11088",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "The Old Mansion Nobodies",
		value: "21D10FC8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Mage's Staff",
		value: "11CDF236",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Hammer Staff",
		value: "11CDF246",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Victory Bell",
		value: "11CDF256",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Comet Staff",
		value: "11CDF276",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Lord's Broom",
		value: "11CDF286",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Wisdom Wand",
		value: "11CDF296",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Meteor Staff",
		value: "11CDF266",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Rising Dragon",
		value: "11CDF2A6",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Shaman's Relic",
		value: "11CDF2C6",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Shaman's Relic+",
		value: "11CDF706",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.DONALD,
		description: "Nobody Lance",
		value: "11CDF2B6",
		priority: 0,
		exclude: [],
	},
];
