import { RewardLocation } from "../RewardLocation";
import { RewardLocationType } from "../RewardLocationType";
import { RewardType } from "../RewardType";

export const formRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.form,
		description: "Valor LV2",
		value: "11D1A22E",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Valor LV4",
		value: "11D1A23E",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Valor LV6",
		value: "11D1A24E",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Wisdom LV2",
		value: "11D1A266",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Wisdom LV4",
		value: "11D1A276",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Wisdom LV6",
		value: "11D1A286",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Limit LV2",
		value: "11D1A29E",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Limit LV4",
		value: "11D1A2AE",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Limit LV6",
		value: "11D1A2BE",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Master LV2",
		value: "11D1A2D6",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Master LV4",
		value: "11D1A2E6",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Master LV6",
		value: "11D1A2F6",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Final LV2",
		value: "11D1A30E",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Final LV4",
		value: "11D1A31E",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.form,
		description: "Final LV6",
		value: "11D1A32E",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
];
