import { RewardLocation } from "../RewardLocation";
import { RewardLocationType } from "../RewardLocationType";

export const goofyRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.GOOFY,
		description: "Starting Ability (Goofy)",
		value: "11D16F62",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Starting Ability (Goofy)",
		value: "11D16F62",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Starting Ability (Goofy)",
		value: "11D16F64",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Shan-Yu",
		value: "21D108E8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "The Beast",
		value: "21D10968",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Pete (Olympus Coliseum)",
		value: "21D10848",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Pete (Timeless River)",
		value: "21D109D8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "The Interceptor Barrels",
		value: "21D10D58",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Captain Barbossa",
		value: "11D10AC8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Captain Barbossa",
		value: "11D10ACA",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Treasure Room Heartless",
		value: "21D10E78",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Oogie Boogie",
		value: "21D10A48",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Hyenas 1",
		value: "21D10EC8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Hostile Program",
		value: "21D10C58",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Storm Rider",
		value: "21D10928",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Grim Reaper 1",
		value: "21D11048",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Lock/Shock/Barrel",
		value: "21D10D98",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Hyenas 2",
		value: "21D10EF8",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Zexion",
		value: "21D11178",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Knight's Shield",
		value: "11CDF2E6",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Adamant Shield",
		value: "11CDF2F6",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Chain Gear",
		value: "11CDF306",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Falling Star",
		value: "11CDF326",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Dreamcloud",
		value: "11CDF336",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Knight Defender",
		value: "11CDF346",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Ogre Shield",
		value: "11CDF316",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Genji Shield",
		value: "11CDF356",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Akashic Record",
		value: "11CDF366",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Akashic Record+",
		value: "11CDF716",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.GOOFY,
		description: "Nobody Guard",
		value: "11CDF376",
		priority: 0,
		exclude: [],
	},
];
