import { Rewards } from "../rewards";
import { RewardLocation, RewardLocationType } from "./RewardLocation";

export const landOfDragonsRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Bamboo Grove)",
		value: "11CDF72A",
		reward: Rewards.DARK_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Bamboo Grove)",
		value: "11CDF736",
		reward: Rewards.ETHER,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Bamboo Grove)",
		value: "11CDF742",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Checkpoint)",
		value: "11CDF74E",
		reward: Rewards.HI_POTION,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Checkpoint)",
		value: "11CDF75A",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Mountain Trail)",
		value: "11CDF766",
		reward: Rewards.LIGHTNING_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Mountain Trail)",
		value: "11CDF772",
		reward: Rewards.RECOVERY_RECIPE,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Mountain Trail)",
		value: "11CDF77E",
		reward: Rewards.ETHER,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Mountain Trail)",
		value: "11CDF78A",
		reward: Rewards.MYTHRIL_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Village Cave)",
		value: "11CDF796",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Village Cave)",
		value: "11CDF7A2",
		reward: Rewards.DARK_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Ridge)",
		value: "11CDF7AE",
		reward: Rewards.FROST_SHARD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Ridge)",
		value: "11CDF7BA",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.BIGCHEST,
		description: "The Land of Dragons (Throne Room)",
		value: "11CDF7C6",
		reward: Rewards.TORN_PAGE,
	},
	{
		type: RewardLocationType.BIGCHEST,
		description: "The Land of Dragons (Throne Room)",
		value: "11CDF7D2",
		reward: Rewards.PALACE_MAP,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Throne Room)",
		value: "11CDF7DE",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Throne Room)",
		value: "11CDF7EA",
		reward: Rewards.QUEEN_RECIPE,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Throne Room)",
		value: "11CDF7F6",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.CHEST,
		description: "The Land of Dragons (Throne Room)",
		value: "11CDF802",
		reward: Rewards.OGRE_SHIELD,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Land of Dragons (Throne Room)",
		value: "11CDF80E",
		reward: Rewards.MYTHRIL_CRYSTAL,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Land of Dragons (Throne Room)",
		value: "11CDF81A",
		reward: Rewards.ORICHALCUM,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Encampment Area Map",
		value: "11CE06D2",
		reward: Rewards.ENCAMPMENT_AREA_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "AP Boost (Missions)",
		value: "11CE06C6",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Village Area Map",
		value: "11CE06DE",
		reward: Rewards.VILLAGE_AREA_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Hidden Dragon",
		value: "11CE06EA",
		reward: Rewards.HIDDEN_DRAGON,
	},
];
