import { RewardLocation } from "../RewardLocation";
import { RewardLocationType } from "../RewardLocationType";
import { RewardType } from "../RewardType";

export const popupRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.POPUP,
		description: "Twilight Town Map",
		value: "11CE0636",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Munny Pouch (Olette)",
		value: "11CE0606",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: '"The Struggle" Trophy',
		value: "11CE062A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Namine's Sketches",
		value: "11CE0642",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Mansion Map",
		value: "11CE064E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Munny Pouch (Mickey)",
		value: "11CE065A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Crystal Orb",
		value: "11CE0666",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Star Seeker",
		value: "11CE0672",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Valor Form",
		value: "11CE067E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Marketplace Map",
		value: "11CE068A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Membership Card",
		value: "11CE0696",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Blizzard Element (Hollow Bastion 1)",
		value: "11CE06A2",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Encampment Area Map",
		value: "11CE06D2",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "AP Boost (Missions)",
		value: "11CE06C6",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Village Area Map",
		value: "11CE06DE",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Hidden Dragon",
		value: "11CE06EA",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Cure Element (Beast's Castle)",
		value: "11CE06F6",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Baseball Charm",
		value: "11CE0702",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Coliseum Map",
		value: "11CE070E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Olympus Stone",
		value: "11CE071A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Hero's Crest",
		value: "11CE0726",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Disney Castle Map",
		value: "11CE0756",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Window of Time Map",
		value: "11CE076E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Monochrome",
		value: "11CE0732",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Wisdom Form",
		value: "11CE0762",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Isla de Muerta Map",
		value: "11CE077A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Follow the Wind",
		value: "11CE0786",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Agrabah Map",
		value: "11CE0792",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Lamp Charm",
		value: "11CE079E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Magnet Element (Halloween Town)",
		value: "11CE07AA",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Circle of Life",
		value: "11CE07B6",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Fire Upgrade (Pride Lands)",
		value: "11CE07C2",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Seifer's Trophy",
		value: "11CE07E6",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Oathkeeper",
		value: "11CE07F2",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Limit Form",
		value: "11CE07FE",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Master Form",
		value: "11CE080A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Photon Debugger",
		value: "11CE0816",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Cure Upgrade (Hollow Bastion)",
		value: "11CE0822",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Ice Cream",
		value: "11CE082E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Picture",
		value: "11CE083A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Undersea Kingdom Map",
		value: "11CE0846",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Rumbling Rose",
		value: "11CE0852",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Castle Walls Map",
		value: "11CE085E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Auron's Statue",
		value: "11CE0882",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Guardian Soul",
		value: "11CE088E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Cursed Medallion",
		value: "11CE086A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Ship Graveyard Map",
		value: "11CE0876",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Wishing Lamp",
		value: "11CE08B2",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Present",
		value: "11CE08BE",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Decoy Presents",
		value: "11CE08CA",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Decisive Pumpkin",
		value: "11CE08D6",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Mysterious Abyss",
		value: "11CE08E2",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Blizzard Upgrade (Atlantica)",
		value: "11CE08EE",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Orichalcum+ (Atlantica)",
		value: "11CE08FA",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Sweet Memories",
		value: "11CE0906",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Spooky Cave Map",
		value: "11CE0912",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Cure Upgrade (100 Acre Wood)",
		value: "11CE091E",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Orichalcum+ (100 Acre Wood)",
		value: "11CE092A",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Sleeping Lion",
		value: "11CE0936",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Fenrir",
		value: "11CE0942",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Bond of Flame",
		value: "11CE0966",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Two Become One",
		value: "11CE0972",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Oblivion",
		value: "11CE097E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Castle That Never Was Map",
		value: "11CE098A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Protect Belt (Pain & Panic Cup)",
		value: "11CE073E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Serenity Gem (Pain & Panic Cup)",
		value: "11CE074A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Rising Dragon (Cerberus Cup)",
		value: "11CE07CE",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Serenity Crystal (Cerberus Cup)",
		value: "11CE07DA",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Genji Shield (Titan Cup)",
		value: "11CE089A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Skillfull Ring (Titan Cup)",
		value: "11CE08A6",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Fatal Crest (Goddess of Fate Cup)",
		value: "11CE094E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Orichalcum+ (Goddess of Fate Cup)",
		value: "11CE095A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 1 (1,000 Heartless)",
		value: "11CE09A2",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 2 (Station Plaza Nobodies)",
		value: "11CE09AE",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 3 (Xigbar)",
		value: "11CE09BA",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 4 (Xaldin)",
		value: "11CE09C6",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 5 (OC Demyx)",
		value: "11CE09D2",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 6 (Grim Reaper 2)",
		value: "11CE09DE",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 7 (Bailey Nobodies)",
		value: "11CE09EA",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 8 (Roxas)",
		value: "11CE09F6",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 9 (Luxord)",
		value: "11CE0A02",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 10 (Twilight Town 3)",
		value: "11CE0A0E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 11 (Before Xemnas 1)",
		value: "11CE0A1A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 12 (Saix)",
		value: "11CE0A26",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 13 (Xemnas 1)",
		value: "11CE0A32",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Road to Discovery",
		value: "11CE0A3E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Strength Beyond Strength",
		value: "11CE0A4A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Book of Shadows",
		value: "11CE0A56",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Cloaked Thunder",
		value: "11CE0A62",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Eternal Blossom",
		value: "11CE0A6E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Power Boost (Data Xemnas)",
		value: "11CE0ADA",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Defense Boost (Data Xigbar)",
		value: "11CE0AE6",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Defense Boost (Data Xaldin)",
		value: "11CE0AC2",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Lost Illusion (Vexen)",
		value: "11CE0A7A",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Lost Illusion (Lexaeus)",
		value: "11CE0A86",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Lost Illusion (Zexion)",
		value: "11CE0A92",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Defense Boost (Data Saix)",
		value: "11CE0AF2",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Magic Boost (Data Axel)",
		value: "11CE0ACE",
		priority: 0,
		exclude: [RewardType.FORM],
	},
	{
		type: RewardLocationType.POPUP,
		description: "AP Boost (Data Demyx)",
		value: "11CE0AB6",
		priority: 0,
		exclude: [RewardType.FORM],
	},
	{
		type: RewardLocationType.POPUP,
		description: "AP Boost (Data Luxord)",
		value: "11CE0AFE",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Lost Illusion (Marluxia)",
		value: "11CE0AAA",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Lost Illusion (Larxene)",
		value: "11CE0A9E",
		priority: 0,
		exclude: [],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Magic Boost (Data Roxas)",
		value: "11CE0B0A",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Proof of Connection",
		value: "11CE0B16",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Manifest Illusion (Lingering Will)",
		value: "11CE0B22",
		priority: 0,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
];
