import { Rewards } from "../rewards";
import { RewardType } from "../rewards/Reward";
import { RewardLocation, RewardLocationType } from "./RewardLocation";

export const popupRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.POPUP,
		description: "Twilight Town Map",
		value: "11CE0636",
		reward: Rewards.TWILIGHT_TOWN_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Munny Pouch (Olette)",
		value: "11CE0606",
		reward: Rewards.MUNNY_POUCH_OLETTE,
	},
	{
		type: RewardLocationType.POPUP,
		description: '"The Struggle" Trophy',
		value: "11CE062A",
		reward: Rewards.STRUGGLE_TROPHY,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Namine's Sketches",
		value: "11CE0642",
		reward: Rewards.NAMINE_SKETCHES,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Mansion Map",
		value: "11CE064E",
		reward: Rewards.MANSION_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Munny Pouch (Mickey)",
		value: "11CE065A",
		reward: Rewards.MUNNY_POUCH_MICKEY,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Crystal Orb",
		value: "11CE0666",
		reward: Rewards.CRYSTAL_ORB,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Star Seeker",
		value: "11CE0672",
		reward: Rewards.STAR_SEEKER,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Valor Form",
		value: "11CE067E",
		reward: Rewards.VALOR_FORM,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Marketplace Map",
		value: "11CE068A",
		reward: Rewards.MARKETPLACE_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Membership Card",
		value: "11CE0696",
		reward: Rewards.MEMBERSHIP_CARD,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Blizzard Element (Hollow Bastion 1)",
		value: "11CE06A2",
		reward: Rewards.BLIZZARD,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Encampment Area Map",
		value: "11CE06D2",
		reward: Rewards.ENCAMPMENT_AREA_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "AP Boost (Missions)",
		value: "11CE06C6",
		reward: Rewards.AP_BOOST,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Village Area Map",
		value: "11CE06DE",
		reward: Rewards.VILLAGE_AREA_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Hidden Dragon",
		value: "11CE06EA",
		reward: Rewards.HIDDEN_DRAGON,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Cure Element (Beast's Castle)",
		value: "11CE06F6",
		reward: Rewards.CURE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Baseball Charm",
		value: "11CE0702",
		reward: Rewards.BASEBALL_CHARM,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Coliseum Map",
		value: "11CE070E",
		reward: Rewards.COLISEUM_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Olympus Stone",
		value: "11CE071A",
		reward: Rewards.OLYMPUS_STONE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Hero's Crest",
		value: "11CE0726",
		reward: Rewards.HEROS_CREST,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Disney Castle Map",
		value: "11CE0756",
		reward: Rewards.DISNEY_CASTLE_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Window of Time Map",
		value: "11CE076E",
		reward: Rewards.WINDOW_OF_TIME_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Monochrome",
		value: "11CE0732",
		reward: Rewards.MONOCHROME,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Wisdom Form",
		value: "11CE0762",
		reward: Rewards.WISDOM_FORM,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Isla de Muerta Map",
		value: "11CE077A",
		reward: Rewards.ISLA_DE_MUERTA_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Follow the Wind",
		value: "11CE0786",
		reward: Rewards.FOLLOW_THE_WIND,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Agrabah Map",
		value: "11CE0792",
		reward: Rewards.AGRABAH_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Lamp Charm",
		value: "11CE079E",
		reward: Rewards.LAMP_CHARM,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Magnet Element (Halloween Town)",
		value: "11CE07AA",
		reward: Rewards.MAGNET,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Circle of Life",
		value: "11CE07B6",
		reward: Rewards.CIRCLE_OF_LIFE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Fire Upgrade (Pride Lands)",
		value: "11CE07C2",
		reward: Rewards.FIRE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Seifer's Trophy",
		value: "11CE07E6",
		reward: Rewards.SEIFERS_TROPHY,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Oathkeeper",
		value: "11CE07F2",
		reward: Rewards.OATHKEEPER,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Limit Form",
		value: "11CE07FE",
		reward: Rewards.LIMIT_FORM,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Master Form",
		value: "11CE080A",
		reward: Rewards.MASTER_FORM,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Photon Debugger",
		value: "11CE0816",
		reward: Rewards.PHOTON_DEBUGGER,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Cure Upgrade (Hollow Bastion)",
		value: "11CE0822",
		reward: Rewards.CURE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Ice Cream",
		value: "11CE082E",
		reward: Rewards.ICE_CREAM,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Picture",
		value: "11CE083A",
		reward: Rewards.PICTURE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Undersea Kingdom Map",
		value: "11CE0846",
		reward: Rewards.UNDERSEA_KINGDOM_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Rumbling Rose",
		value: "11CE0852",
		reward: Rewards.RUMBLING_ROSE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Castle Walls Map",
		value: "11CE085E",
		reward: Rewards.CASTLE_WALLS_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Auron's Statue",
		value: "11CE0882",
		reward: Rewards.AURONS_STATUE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Guardian Soul",
		value: "11CE088E",
		reward: Rewards.GUARDIAN_SOUL,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Cursed Medallion",
		value: "11CE086A",
		reward: Rewards.CURSED_MEDALLION,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Ship Graveyard Map",
		value: "11CE0876",
		reward: Rewards.SHIP_GRAVEYARD_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Wishing Lamp",
		value: "11CE08B2",
		reward: Rewards.WISHING_LAMP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Present",
		value: "11CE08BE",
		reward: Rewards.PRESENTS,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Decoy Presents",
		value: "11CE08CA",
		reward: Rewards.DECOY_PRESENTS,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Decisive Pumpkin",
		value: "11CE08D6",
		reward: Rewards.DECISIVE_PUMPKIN,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Mysterious Abyss",
		value: "11CE08E2",
		reward: Rewards.MYSTERIOUS_ABYSS,
		exclude: [RewardType.FORM, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Blizzard Upgrade (Atlantica)",
		value: "11CE08EE",
		reward: Rewards.BLIZZARD,
		exclude: [RewardType.FORM, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Orichalcum+ (Atlantica)",
		value: "11CE08FA",
		reward: Rewards.ORICHALCUM_PLUS,
		exclude: [RewardType.FORM, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Sweet Memories",
		value: "11CE0906",
		reward: Rewards.SWEET_MEMORIES,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Spooky Cave Map",
		value: "11CE0912",
		reward: Rewards.SPOOKY_CAVE_MAP,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Cure Upgrade (100 Acre Wood)",
		value: "11CE091E",
		reward: Rewards.CURE,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Orichalcum+ (100 Acre Wood)",
		value: "11CE092A",
		reward: Rewards.ORICHALCUM_PLUS,
		exclude: [RewardType.FORM, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Sleeping Lion",
		value: "11CE0936",
		reward: Rewards.SLEEPING_LION,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Fenrir",
		value: "11CE0942",
		reward: Rewards.FENRIR,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Bond of Flame",
		value: "11CE0966",
		reward: Rewards.BOND_OF_FLAME,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Two Become One",
		value: "11CE0972",
		reward: Rewards.TWO_BECOME_ONE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Oblivion",
		value: "11CE097E",
		reward: Rewards.OBLIVION,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Castle That Never Was Map",
		value: "11CE098A",
		reward: Rewards.CASTLE_THAT_NEVER_WAS_MAP,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Protect Belt (Pain & Panic Cup)",
		value: "11CE073E",
		reward: Rewards.PROTECT_BELT,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Serenity Gem (Pain & Panic Cup)",
		value: "11CE074A",
		reward: Rewards.SERENITY_GEM,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Rising Dragon (Cerberus Cup)",
		value: "11CE07CE",
		reward: Rewards.RISING_DRAGON,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Serenity Crystal (Cerberus Cup)",
		value: "11CE07DA",
		reward: Rewards.SERENITY_CRYSTAL,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Genji Shield (Titan Cup)",
		value: "11CE089A",
		reward: Rewards.GENJI_SHIELD,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Skillfull Ring (Titan Cup)",
		value: "11CE08A6",
		reward: Rewards.SKILLFUL_RING,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Fatal Crest (Goddess of Fate Cup)",
		value: "11CE094E",
		reward: Rewards.FATAL_CREST,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Orichalcum+ (Goddess of Fate Cup)",
		value: "11CE095A",
		reward: Rewards.ORICHALCUM_PLUS,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 1 (1,000 Heartless)",
		value: "11CE09A2",
		reward: Rewards.REPORT_ONE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 2 (Station Plaza Nobodies)",
		value: "11CE09AE",
		reward: Rewards.REPORT_TWO,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 3 (Xigbar)",
		value: "11CE09BA",
		reward: Rewards.REPORT_THREE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 4 (Xaldin)",
		value: "11CE09C6",
		reward: Rewards.REPORT_FOUR,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 5 (OC Demyx)",
		value: "11CE09D2",
		reward: Rewards.REPORT_FIVE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 6 (Grim Reaper 2)",
		value: "11CE09DE",
		reward: Rewards.REPORT_SIX,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 7 (Bailey Nobodies)",
		value: "11CE09EA",
		reward: Rewards.REPORT_SEVEN,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 8 (Roxas)",
		value: "11CE09F6",
		reward: Rewards.REPORT_EIGHT,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 9 (Luxord)",
		value: "11CE0A02",
		reward: Rewards.REPORT_NINE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 10 (Twilight Town 3)",
		value: "11CE0A0E",
		reward: Rewards.REPORT_TEN,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 11 (Before Xemnas 1)",
		value: "11CE0A1A",
		reward: Rewards.REPORT_ELEVEN,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 12 (Saix)",
		value: "11CE0A26",
		reward: Rewards.REPORT_TWELVE,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Secret Ansem's Report 13 (Xemnas 1)",
		value: "11CE0A32",
		reward: Rewards.REPORT_THIRTEEN,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Road to Discovery",
		value: "11CE0A3E",
		reward: Rewards.ROAD_TO_DISCOVERY,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Strength Beyond Strength",
		value: "11CE0A4A",
		reward: Rewards.STRENGTH_BEYOND_STRENGTH,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Book of Shadows",
		value: "11CE0A56",
		reward: Rewards.BOOK_OF_SHADOWS,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Cloaked Thunder",
		value: "11CE0A62",
		reward: Rewards.CLOAKED_THUNDER,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Eternal Blossom",
		value: "11CE0A6E",
		reward: Rewards.ETERNAL_BLOSSOM,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Power Boost (Data Xemnas)",
		value: "11CE0ADA",
		reward: Rewards.POWER_BOOST,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Defense Boost (Data Xigbar)",
		value: "11CE0AE6",
		reward: Rewards.DEFENSE_BOOST,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Defense Boost (Data Xaldin)",
		value: "11CE0AC2",
		reward: Rewards.DEFENSE_BOOST,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Lost Illusion (Vexen)",
		value: "11CE0A7A",
		reward: Rewards.LOST_ILLUSION,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Lost Illusion (Lexaeus)",
		value: "11CE0A86",
		reward: Rewards.LOST_ILLUSION,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Lost Illusion (Zexion)",
		value: "11CE0A92",
		reward: Rewards.LOST_ILLUSION,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Defense Boost (Data Saix)",
		value: "11CE0AF2",
		reward: Rewards.DEFENSE_BOOST,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Magic Boost (Data Axel)",
		value: "11CE0ACE",
		reward: Rewards.MAGIC_BOOST,
		exclude: [RewardType.FORM],
	},
	{
		type: RewardLocationType.POPUP,
		description: "AP Boost (Data Demyx)",
		value: "11CE0AB6",
		reward: Rewards.AP_BOOST,
		exclude: [RewardType.FORM],
	},
	{
		type: RewardLocationType.POPUP,
		description: "AP Boost (Data Luxord)",
		value: "11CE0AFE",
		reward: Rewards.AP_BOOST,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Lost Illusion (Marluxia)",
		value: "11CE0AAA",
		reward: Rewards.LOST_ILLUSION,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Lost Illusion (Larxene)",
		value: "11CE0A9E",
		reward: Rewards.LOST_ILLUSION,
	},
	{
		type: RewardLocationType.POPUP,
		description: "Magic Boost (Data Roxas)",
		value: "11CE0B0A",
		reward: Rewards.MAGIC_BOOST,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Proof of Connection",
		value: "11CE0B16",
		reward: Rewards.PROOF_OF_CONNECTION,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
	{
		type: RewardLocationType.POPUP,
		description: "Manifest Illusion (Lingering Will)",
		value: "11CE0B22",
		reward: Rewards.MANIFEST_ILLUSION,
		exclude: [RewardType.FORM, RewardType.TORNPAGE, RewardType.SPELL],
	},
];
