import { RewardLocation } from "../RewardLocation";
import { RewardLocationType } from "../RewardLocationType";

export const twilightTownRewardLocations: RewardLocation[] = [
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (The Old Mansion)",
		value: "11CE022E",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (The Old Mansion)",
		value: "11CE023A",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (The Woods)",
		value: "11CE0246",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (The Woods)",
		value: "11CE0252",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (The Woods)",
		value: "11CE025E",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Tram Common)",
		value: "11CE026A",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Tram Common)",
		value: "11CE0276",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Tram Common)",
		value: "11CE0282",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Tram Common)",
		value: "11CE028E",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Tram Common)",
		value: "11CE029A",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Tram Common)",
		value: "11CE02A6",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Tram Common)",
		value: "11CE02B2",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Central Station)",
		value: "11CE02BE",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Central Station)",
		value: "11CE02CA",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Central Station)",
		value: "11CE02D6",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (The Tower)",
		value: "11CE02E2",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (The Tower)",
		value: "11CE02EE",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (The Tower)",
		value: "11CE02FA",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Tower Entryway)",
		value: "11CE0306",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Tower Entryway)",
		value: "11CE0312",
		priority: 0,
	},
	{
		type: RewardLocationType.BIGCHEST,
		description: "Twilight Town (Sorcerer's Loft)",
		value: "11CE031E",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Tower Wardrobe)",
		value: "11CE032A",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Underground Concourse)",
		value: "11CE0336",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Underground Concourse)",
		value: "11CE0342",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Underground Concourse)",
		value: "11CE034E",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Underground Concourse)",
		value: "11CE035A",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Tunnelway)",
		value: "11CE0366",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Tunnelway)",
		value: "11CE0372",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Sunset Terrace)",
		value: "11CE037E",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Sunset Terrace)",
		value: "11CE038A",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Sunset Terrace)",
		value: "11CE0396",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Sunset Terrace)",
		value: "11CE03A2",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Mansion Foyer)",
		value: "11CE03AE",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Mansion Foyer)",
		value: "11CE03BA",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Mansion Foyer)",
		value: "11CE03C6",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Mansion Dining Room)",
		value: "11CE03D2",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Mansion Dining Room)",
		value: "11CE03DE",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Mansion Library)",
		value: "11CE03EA",
		priority: 0,
	},
	{
		type: RewardLocationType.CHEST,
		description: "Twilight Town (Mansion Basement Corridor)",
		value: "11CE03F6",
		priority: 0,
	},
];
